export const BLOG_CONTENT: Record<string, string[]> = {
  "dualtron-freins-nutt-purge": [
    "Les trottinettes Dualtron (Thunder, Ultra, Spider, Victor…) sont équipées en grande majorité de freins NUTT hydrauliques ou de freins à disque performants. Un bon réglage est indispensable pour rouler en sécurité, surtout à vitesses élevées.",
    "Vérifiez régulièrement l'usure des plaquettes et l'état du disque. Un grincement ou une perte de mordant indique souvent des plaquettes usées ou un disque voilé. La purge du circuit hydraulique élimine l'air qui rend le levier « mou ».",
    "Pour une purge complète ou le remplacement de plaquettes NUTT, comptez sur l'expérience d'un atelier équipé. À Répatech à Saint-Fons, nous entretenons les Dualtron du Rhône : réglage, purge, changement de disques et câbles si besoin.",
    "N'attendez pas que le frein disparaisse complètement : un frein défaillant sur une Dualtron, c'est un risque majeur pour vous et pour les autres usagers.",
  ],
  "kukirin-g4-entretien-pneus": [
    "Les Kukirin G2 et G4 roulent souvent avec des pneus 10 ou 11 pouces, en chambre à air ou en configuration tubeless selon le modèle. Une bonne pression limite les crevaisons et préserve l'autonomie.",
    "Sous-gonflé, le pneu s'écrase sur les chocs et se perce plus facilement sur les nids-de-poule lyonnais. Sur-gonflé, vous perdez en confort et en adhérence, surtout sous la pluie.",
    "Pour limiter les crevaisons, nous recommandons la pose d'une bande anti-crevaison (pneu à bande) entre le pneu et la chambre à air. Cette protection en caoutchouc ou en gel absorbe les pointes de verre et les éclats avant qu'ils ne perforent le tube — particulièrement utile sur le G2 et le G4 en usage quotidien.",
    "Contrôlez la pression toutes les deux semaines. Repérez les corps étrangers (verre, clou) avant qu'ils ne traversent complètement la chambre. En cas de crevaison récurrente, vérifiez aussi l'état de la jante.",
    "Chez Répatech, nous remplaçons pneus, chambres à air et bandes anti-crevaison sur Kukirin et autres marques — tarifs affichés dès 40 € selon la taille.",
  ],
  "xiaomi-m365-crevaison-reparation": [
    "La Xiaomi M365, Pro, Essential ou Pro 2 reste une référence sur le marché, avec ses pneus 8,5 pouces et son frein à tambour arrière. À Saint-Fons, on en voit régulièrement — aux côtés de Kukirin, Dualtron et bien d'autres marques — mais ce n'est pas le modèle le plus fréquent en atelier.",
    "Première astuce : vérifiez la pression toutes les semaines si vous roulez tous les jours. Un pneu sous-gonflé s'écrase sur les chocs, usure prématurée et crevaisons assurées. Comptez en général autour de 3,5 bar (50 PSI) sur la M365 — le chiffre exact est indiqué sur le flanc du pneu.",
    "Évitez de monter ou descendre les trottoirs en roulant et ralentissez sur les zones gravillonnées ou mal pavées. Sur une Xiaomi, la chambre à air est fine : un éclat de verre peut suffire, surtout si le pneu manque de pression.",
    "Pneu mou du matin au soir ? Crevaison lente probable. Gonflez pour regagner l'atelier ou chez vous, mais ne repartez pas des heures sur un pneu qui se dégonfle à nouveau — vous risquez d'abîmer la jante ou le moteur arrière.",
    "Crevaison franche, roue bloquée, bruit de frottement ou pneu déchiré : ne tentez pas un démontage maison. Sur ces modèles, la roue arrière est liée au frein à tambour et au moteur — un mauvais montage casse souvent le câble ou pince la chambre à air.",
    "C'est précisément pour ça qu'on existe : à Répatech, l'atelier trottinette s'occupe du changement de pneu, de la chambre à air et de la pose de bande anti-crevaison si vous le souhaitez. Passez avec votre Xiaomi ou appelez-nous — diagnostic et tarif clair avant intervention.",
  ],
  "trottinette-ne-demarre-plus": [
    "Quand une trottinette ne démarre plus, plusieurs causes reviennent en atelier : batterie déchargée ou HS, contrôleur grillé, connecteur oxydé, frein moteur bloqué ou BMS en protection.",
    "Commencez par une charge complète sur le chargeur d'origine. Vérifiez que le voyant du chargeur s'allume. Testez aussi le levier de frein : sur certains modèles, un frein serré bloque le moteur.",
    "Kukirin, Xiaomi, Dualtron — chaque marque a ses points faibles. Un diagnostic approfondi au multimètre permet d'identifier la panne sans remplacer inutilement toute l'électronique.",
    "À Répatech, le diagnostic approfondi trottinette est proposé dès 30 €, déduit de la réparation si vous acceptez le devis.",
  ],
  "dualtron-batterie-ne-charge-plus": [
    "Une Dualtron qui ne charge plus peut souffrir d'un chargeur défectueux, d'une prise DC endommagée, d'un BMS en sécurité ou de cellules batterie usées.",
    "Vérifiez d'abord le chargeur sur une prise différente et inspectez le connecteur (broches tordues, traces de brûlure). Si la charge s'arrête à un pourcentage fixe, le BMS limite peut-être la charge pour protéger des cellules faibles.",
    "Ne forcez jamais une batterie qui chauffe ou gonfle : c'est un risque d'incendie. Débranchez et consultez un professionnel.",
    "Répatech réalise le diagnostic batterie Dualtron à Saint-Fons et propose remplacement ou reconditionnement sur devis, selon votre modèle et la capacité souhaitée.",
  ],
  "xiaomi-codes-erreur-diagnostic": [
    "Les Xiaomi affichent parfois des codes via l'application Mi Home, des clignotements du voyant ou des bips au démarrage. Chaque signal correspond à un type de panne : frein, communication moteur, surchauffe, etc.",
    "Avant de démonter le deck, notez le code exact et la fréquence des clignotements. Une mise à jour firmware ou un simple reset peut parfois suffire — mais pas toujours.",
    "Les erreurs liées au contrôleur ou au câblage interne demandent un outillage adapté. Un mauvais branchement après réparation maison aggrave souvent la facture.",
    "Nos techniciens à Saint-Fons connaissent les pannes récurrentes M365 / Pro 2 et vous orientent vers la réparation la plus économique.",
  ],
  "kukirin-batterie-hiver": [
    "Le froid réduit nettement l'autonomie des batteries lithium. Sur un Kukirin G2 ou G4, il n'est pas rare de perdre 20 à 40 % de range en hiver.",
    "Stockez la trottinette à l'abri, idéalement entre 10 et 25 °C. Évitez de la laisser dehors la nuit. Chargez à environ 50 à 70 % si vous ne l'utilisez pas plusieurs semaines.",
    "Avant de rouler par grand froid, laissez la batterie reprendre quelques minutes en intérieur. Ne chargez pas une batterie gelée.",
    "Si l'autonomie ne revient plus au printemps, un contrôle des cellules en atelier permet de savoir si un remplacement est nécessaire.",
  ],
  "gonflage-pneus-trottinette": [
    "La pression idéale dépend du diamètre : environ 3,5 à 4,5 bar sur du 8 pouces, un peu moins sur du 10 ou 11 pouces selon le poids du pilote. Consultez le flanc du pneu pour la valeur max.",
    "Un pneu mou augmente la consommation énergétique et l'usure. Il percera plus vite sur les routes du Rhône. Un pneu trop dur transmet tous les chocs au cadre et au pilote.",
    "Utilisez une pompe avec manomètre — les stations-service peuvent sur-gonfler les petites chambres à air. Contrôlez les deux roues, pas seulement l'avant.",
    "Répatech peut gonfler, réparer ou remplacer vos pneus trottinette lors de votre passage à l'atelier.",
  ],
  "verifier-freins-avant-rouler": [
    "Avant chaque sortie, 30 secondes suffisent : testez les deux leviers, vérifiez que la roue arrière se bloque correctement, inspectez visuellement l'épaisseur des plaquettes.",
    "Après la pluie, l'eau réduit temporairement l'efficacité du frein — serrez légèrement si le câble a pris le jeu, sans exagérer.",
    "Sur Dualtron, Kukirin ou Xiaomi, un frein mal réglé use prématurément le disque et peut déclencher une erreur moteur.",
    "Si le levier touche le guidon ou si vous entendez un métal sur métal, passez à l'atelier avant de reprendre la route.",
  ],
  "prolonger-duree-vie-batterie": [
    "Les batteries lithium ont une durée de vie limitée en cycles de charge. Évitez les décharges complètes répétées et les charges prolongées à 100 % si vous stockez l'appareil.",
    "Utilisez le chargeur d'origine ou un modèle certifié avec les bonnes tensions. Une charge rapide non adaptée chauffe les cellules et les vieillit plus vite.",
    "Même logique pour les smartphones : cycles partiels, températures modérées, pas de charge sous oreiller la nuit si l'appareil chauffe.",
    "Quand l'autonomie chute durablement, un remplacement batterie chez Répatech redonne une seconde vie à votre trottinette ou téléphone — souvent moins cher qu'un appareil neuf.",
  ],
  "pieces-detachees-origine-compatibles": [
    "Pièces d'origine, compatibles premium ou low-cost : le choix impacte directement la durée de vie et la sécurité, surtout pour freins, pneus et batteries.",
    "Un écran iPhone compatible bas de gamme peut perdre la luminosité ou le tactile en quelques mois. Une cellule batterie non certifiée présente un risque de gonflement.",
    "Chez Répatech, nous privilégions des pièces fiables avec garantie 6 mois trottinette / 3 mois téléphone, sous certaines conditions.",
    "Demandez toujours un devis détaillé avant réparation : qualité de la pièce, main d'œuvre incluse et délai d'intervention.",
  ],
  "dualtron-checklist-entretien": [
    "Un entretien régulier prolonge la vie d'une Dualtron Thunder, Ultra ou Mini : serrages des vis de potence et de deck, contrôle du jeu de direction, graissage des points prévus par le constructeur.",
    "Inspectez les câbles du moteur et du frein régénétatif, les connecteurs sous le deck et l'état des suspensions si votre modèle en est équipé.",
    "Un contrôle électrique annuel permet de détecter une corrosion ou une surchauffe avant panne majeure.",
    "Vous pouvez faire une partie de l'entretien vous-même ; pour le reste, l'équipe Répatech à Saint-Fons prend le relais avec des tarifs transparents.",
  ],
  "ecran-fissure-reparer-ou-racheter": [
    "Un écran fissuré reste utilisable un temps, mais les fissures s'aggravent, la dalle perd en étanchéité et les éclats de verre peuvent blesser.",
    "Sur iPhone ou Samsung, la réparation en atelier local coûte souvent une fraction du prix d'un neuf — surtout pour les modèles récents encore performants.",
    "Réparer, c'est aussi éviter l'impact environnemental d'un téléphone jeté trop tôt. Chez Répatech, un verre trempé est offert à chaque changement d'écran iPhone.",
    "Garantie 3 mois sur les réparations smartphone, sous certaines conditions. Comparez le devis réparation vs rachat avant de décider.",
  ],
  "reparation-iphone-saint-fons": [
    "Faire réparer son iPhone près de chez soi à Saint-Fons, c'est gagner en délais : pas d'envoi postal, pas d'attente de 10 jours sans téléphone.",
    "Un atelier de proximité connaît les modèles les plus courants dans le 69 et maintient des pièces en stock pour les écrans iPhone les plus demandés.",
    "Tarifs affichés, montage inclus, verre trempé offert — vous savez à quoi vous attendre avant de déposer l'appareil.",
    "Accessible en TCL (bus C12, 60, 93), Répatech accueille les clients de Saint-Fons, Vénissieux, Lyon et tout le sud lyonnais.",
  ],
  "verre-trempe-ecran-reparation": [
    "Après un changement d'écran, la dalle neuve est vulnérable. Un verre trempé posé immédiatement protège contre les chocs du quotidien.",
    "Nettoyez la surface avec un chiffon microfibre sans poussière. Centrez le verre, laissez adhérer sans bulles d'air. Attendez quelques heures avant de mettre une coque serrée.",
    "Chez Répatech, le verre trempé est inclus à chaque réparation d'écran iPhone — un détail qui prolonge la durée de vie de votre réparation.",
    "Pour les autres marques, demandez nos protections disponibles en boutique lors de la réparation.",
  ],
  "reparer-plutot-racheter": [
    "Trottinette ou smartphone, jeter un appareil réparable génère des déchets électroniques et un coût inutile. La réparation locale soutient aussi l'économie de votre quartier.",
    "Un moteur, une batterie ou un écran remplacés redonnent des années de service à un engin déjà amorti. Le reconditionné professionnel, c'est la même logique à plus grande échelle.",
    "À Saint-Fons, Répatech privilégie la réparation d'abord : diagnostic, devis clair, intervention rapide. Rachat neuf seulement quand la réparation n'est plus viable.",
    "Vous hésitez ? Appelez ou passez avec votre appareil : nous vous disons honnêtement si ça vaut le coup de réparer.",
  ],
};
